version: '3.5'

services:
  p2ptrading-app:
    image: p2p-trading-app:final
    environment:
      - VIRTUAL_HOST=p2ptrading-app.dev4.ari-bip.eu
      - VIRTUAL_PORT=80
    networks:
      - uself_net

  p2ptrading-server:
    image: server:test
    environment:
      - VIRTUAL_HOST=p2ptrading-server.dev4.ari-bip.eu
      - VIRTUAL_PORT=3000
    volumes:
      - /home/david.casalod/go/src/github.com/david/fabric-samples:/home/david.casalod/go/src/github.com/david/fabric-samples
    networks:
      - uself_net

networks:
  uself_net:
    external: true
