version: '3.5'

services:
  p2p:
    image: p2p:test4
    environment:
      - VIRTUAL_HOST=p2p.atos.bd4opem.eu
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=p2p.atos.bd4opem.eu
    networks:
      - uself_net

  p2ptrading-server:
    image: p2pserver:test
    environment:
      - VIRTUAL_HOST=p2ptrading-server.dev4.ari-bip.eu
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=p2ptrading-server.dev4.ari-bip.eu
    volumes:
      - /home/david.casalod/go/src/github.com/david/fabric-samples:/home/david.casalod/go/src/github.com/david/fabric-samples
    networks:
      - uself_net

networks:
  uself_net:
    external: true
