version: '3.5'

services:
  p2ptrading-app:
    image: p2ptrading-app:prueba
    environment:
      - VIRTUAL_HOST=p2ptrading-app
      - VIRTUAL_PORT=80
    networks:
      - bd4opem_net

  p2ptrading-server:
    image: registry.atosresearch.eu:18473/bd4opem/p2ptrading/p2ptrading-app-server:local_VM
    environment:
      - VIRTUAL_HOST=p2ptrading-server
      - VIRTUAL_PORT=3000
    volumes:
      - /home/david.casalod/go/src/github.com/david/fabric-samples:/home/david.casalod/go/src/github.com/david/fabric-samples
    networks:
      - bd4opem_net

  nginx:
    image: nginx:1.17.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - bd4opem_net

networks:
  bd4opem_net:
    external: true
