version: '3'
services:
  angular:
    # image: <nexus-registry-url>/p2ptrading-app-angular
    image: p2ptrading-app-angular
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=testservice.bd4opem.eu
     

    ports:
      - "80:80"
  server:
    # image: <nexus-registry-url>/p2ptrading-app-server
    image: p2ptrading-app-server
     
    ports:
      - "3000:3000"
