version: '3.5'

services:

  p2ptrading-server:
    image: server:test
    environment:
      - VIRTUAL_HOST=http://p2ptrading-server.dev4.ari-bip.eu
      - VIRTUAL_PORT=3000
    volumes:
      - /home/david.casalod/go/src/github.com/david/fabric-samples:/home/david.casalod/go/src/github.com/david/fabric-samples
    networks:
      - bd4opem_net

networks:
  bd4opem_net:
    external: true
