# Use an official Node.js runtime as a parent image
FROM node:14.17.6-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in package.json
RUN npm install --force

# Expose port 3000
EXPOSE 3000

# Start the app
CMD ["npm", "start"]