# Use an official Node.js runtime as a parent image
FROM node:14.17.6-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in package.json
RUN npm install --force

# Expose port 80
EXPOSE 80

# Start the app
CMD ["npm", "start"]

# FROM node:14-alpine as node
# RUN mkdir -p /app
# WORKDIR /app
# COPY package.json /app/package.json
# RUN npm install --force
# COPY . /app
# #RUN npm run build --prod
# RUN npm run build
# FROM nginx:1.17.1-alpine 
# COPY --from=node /app/dist/template-admin-lte /usr/share/nginx/html
# EXPOSE 80
