#Descomentar app-routing.module.ts canActivate[AuthGuard]

FROM node:14-alpine as node
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app/package.json
RUN npm install --force
COPY . /app

# RUN npm run build --prod
RUN npm run build
FROM nginx:1.17.1-alpine
COPY --from=node /app/dist/template-admin-lte /usr/share/nginx/html
EXPOSE 80

