/**
 * BD4OPEM Account Management module API Specification
 * This document contains the formal specification of the interfaces with Account and Contracting management in the BD4OPEM Marketplace.
 *
 * OpenAPI spec version: 0.0.25
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The contract claims to be issued in the Contract VC
 */
export interface ContractBusinessParameters { 
    /**
     * The accountID that is being issued the contract
     */
    accountID: string;
    /**
     * The type of contract being issued..
     */
    contractType: ContractBusinessParameters.ContractTypeEnum;
    /**
     * Descriptive name for the contract.
     */
    contractName?: string;
    /**
     * Organisation that contracts to provide this
     */
    contractedByOrgID: string;
    /**
     * Email address of user that contracted the service
     */
    contractedByEmail?: string;
    /**
     * Identity of the provider that will fulfill the contract.
     */
    contractProviderID: string;
    /**
     * URL of the provider that will fulfill the contract.
     */
    contractProviderURL?: string;
    /**
     * Start date for the contract.
     */
    contractStart: string;
    /**
     * Start date for the contract.
     */
    contractEnd: string;
    payment?: ContractBusinessParameters.PaymentEnum;
}
export namespace ContractBusinessParameters {
    export type ContractTypeEnum = 'DataUser' | 'ServiceUser' | 'ServiceProvider' | 'DataProvider';
    export const ContractTypeEnum = {
        DataUser: 'DataUser' as ContractTypeEnum,
        ServiceUser: 'ServiceUser' as ContractTypeEnum,
        ServiceProvider: 'ServiceProvider' as ContractTypeEnum,
        DataProvider: 'DataProvider' as ContractTypeEnum
    };
    export type PaymentEnum = 'one_time' | 'monthlyt' | 'yearly' | 'promotional' | 'free';
    export const PaymentEnum = {
        OneTime: 'one_time' as PaymentEnum,
        Monthlyt: 'monthlyt' as PaymentEnum,
        Yearly: 'yearly' as PaymentEnum,
        Promotional: 'promotional' as PaymentEnum,
        Free: 'free' as PaymentEnum
    };
}