/**
 * BD4OPEM Account Management module API Specification
 * This document contains the formal specification of the interfaces with Account and Contracting management in the BD4OPEM Marketplace.
 *
 * OpenAPI spec version: 0.0.25
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContractBusinessParameters } from './contractBusinessParameters';

/**
 * The contract claims to be issued in the Contract VC
 */
export interface ReturnContract { 
    /**
     * The Contract UUID identity
     */
    contractID?: string;
    version?: string;
    /**
     * The status of the contract.
     */
    status?: string;
    business_parameters?: ContractBusinessParameters;
    /**
     * Contract claims specific to a Service User.
     */
    service_parameters?: any;
    data_parameters?: Array<{
        contractID: string;
        oganizationId	: string;
        accrualPeriod: String;
        resourceEndpoint: string;
        offeringType: string;
        granularity: string;

        meteringPoints: Array<any>;
        meteringPointNo: number;
        attributes: Array<any>;
        type: string;
        data_source_id: string;
    }>
}
export namespace ReturnContract {
    export type StatusEnum = 'Active' | 'Suspended' | 'Revoked';
    export const StatusEnum = {
        Active: 'Active' as StatusEnum,
        Suspended: 'Suspended' as StatusEnum,
        Revoked: 'Revoked' as StatusEnum
    };
}